export const categories = [
    { value: "Ficção", label: "Ficção Literária" },
    { value: "Fantasia", label: "Fantasia" },
    { value: "Sci-fi", label: "Ficção Científica" },
    { value: "Romance", label: "Romance" },
    { value: "Técnico", label: "Técnico/Acadêmico" },
    { value: "Biografia", label: "Biografia" },
    { value: "Aventura", label: "Aventura" },
    { value: "Mistério", label: "Mistério" },
    { value: "Suspense", label: "Suspense" },
    { value: "Terror", label: "Terror" },
    { value: "História", label: "História" },
    { value: "Autoajuda", label: "Autoajuda" },
    { value: "Negócios", label: "Negócios" },
    { value: "Infantil", label: "Literatura Infantil" },
    { value: "Juvenil", label: "Literatura Juvenil" },
    { value: "Poesia", label: "Poesia" },
    { value: "Drama", label: "Drama" },
    { value: "Humor", label: "Humor" },
    { value: "Religião", label: "Religião" },
    { value: "Filosofia", label: "Filosofia" },
    { value: "Ciências Sociais", label: "Ciências Sociais" },
    { value: "Política", label: "Política" },
    { value: "Economia", label: "Economia" },
    { value: "Educação", label: "Educação" },
    { value: "Linguística", label: "Linguística" },
    { value: "Artes", label: "Artes" },
    { value: "Fotografia", label: "Fotografia" },
    { value: "Música", label: "Música" },
    { value: "Cinema", label: "Cinema" },
    { value: "Teatro", label: "Teatro" },
    { value: "Arquitetura", label: "Arquitetura" },
    { value: "Design", label: "Design" },
    { value: "Moda", label: "Moda" },
    { value: "Culinária", label: "Culinária" },
    { value: "Viagem", label: "Viagem" },
    { value: "Esportes", label: "Esportes" },
    { value: "Saúde", label: "Saúde" },
    { value: "Medicina", label: "Medicina" },
    { value: "Ciência", label: "Ciência" },
    { value: "Matemática", label: "Matemática" },
    { value: "Física", label: "Física" },
    { value: "Química", label: "Química" },
    { value: "Biologia", label: "Biologia" },
    { value: "Tecnologia", label: "Tecnologia" },
    { value: "Computação", label: "Computação" },
    { value: "Engenharia", label: "Engenharia" },
    { value: "Direito", label: "Direito" },
    { value: "Psicologia", label: "Psicologia" },
    { value: "Sociologia", label: "Sociologia" },
    { value: "Antropologia", label: "Antropologia" },
    { value: "Geografia", label: "Geografia" },
    { value: "Astronomia", label: "Astronomia" },
    { value: "Enciclopédias", label: "Enciclopédias" },
    { value: "Dicionários", label: "Dicionários" },
    { value: "Guias", label: "Guias" },
    { value: "Manuais", label: "Manuais" },
    { value: "Ensaios", label: "Ensaios" },
    { value: "Discursos", label: "Discursos" },
    { value: "Cartas", label: "Cartas" },
    { value: "Memórias", label: "Memórias" },
    { value: "Jornais", label: "Jornais" },
    { value: "Revistas", label: "Revistas" },
    { value: "Quadrinhos", label: "Quadrinhos" },
    { value: "Mangás", label: "Mangás" },
    { value: "Graphic Novels", label: "Graphic Novels" },
    { value: "Contos", label: "Contos" },
    { value: "Novelas", label: "Novelas" },
    { value: "Literatura Clássica", label: "Literatura Clássica" },
    { value: "Literatura Contemporânea", label: "Literatura Contemporânea" },
    { value: "Literatura Brasileira", label: "Literatura Brasileira" },
    { value: "Literatura Estrangeira", label: "Literatura Estrangeira" },
    { value: "Literatura Esotérica", label: "Literatura Esotérica" },
    { value: "Literatura Fantástica", label: "Literatura Fantástica" },
    { value: "Literatura Gótica", label: "Literatura Gótica" },
    { value: "Literatura Histórica", label: "Literatura Histórica" },
    { value: "Literatura Infantil Juvenil", label: "Literatura Infantil Juvenil" },
    { value: "Literatura Naturalista", label: "Literatura Naturalista" },
    { value: "Literatura Parnasianista", label: "Literatura Parnasianista" },
    { value: "Literatura Realista", label: "Literatura Realista" },
];
